title: Hi, there! I'm Raj Dholakia
description: > # this means to ignore newlines until "baseurl:"
  Welcome to this GitHub page about me.
  This page will provide you with details about who I am,
  what I can do and a brief description of my work.
permalink: ':title/'
baseurl: "/radroid" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Raj Dholakia # add your name
author-img: raj-dholakia-2019.jpg # add your photo
about-author: I am a Mechanical (Nuclear) Engineer turned Data Analyst. Helping people and organizations gain business value from large sets of data. # add description
social-twitter: Ra_Droid # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: radroid # add your Github handle
social-linkedin: raj-dholakia # add your Linkedin handle
social-email: raj9dholakia@gmail.com # add your Email address

# Disqus
discus-identifier: radroid # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
